name: Solana Container
on:
  push:
    branches:
      - solana

jobs:
  solana-docker:
    runs-on: ubuntu-latest
    container:
      image: solanalabs/solana:stable
    steps:
      - name: apt-get update
        run: apt-get update
      - name: Solana version
        run: |
          cat /etc/os-release
          solana --version
      - name: Solana Test Validator
        run: solana-test-validator &
      - name: kill solana-test-validator process
        run: killall -9 solana-test-validator