name: Solana Container
on:
  push:
    branches:
      - solana

jobs:
  solana-docker:
    runs-on: ubuntu-latest
    container:
      image: solanalabs/solana:stable
    steps:
      - name: apt-get
        run: apt-get install procps # pkill
      - name: Solana version
        run: |
          cat /etc/os-release
          solana --version
      - name: Solana Test Validator
        run: |
          solana-test-validator &
      - name: Kill Solana Test Validator Process
        run: |
          pkill solana-test-validator